# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zakaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 493)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_fio = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_fio.setGeometry(QtCore.QRect(70, 60, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_fio.setFont(font)
        self.lineEdit_fio.setText("")
        self.lineEdit_fio.setObjectName("lineEdit_fio")
        self.lineEdit_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_phone.setGeometry(QtCore.QRect(70, 130, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_phone.setFont(font)
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.pushButton_ofzakaz = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ofzakaz.setGeometry(QtCore.QRect(70, 350, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_ofzakaz.setFont(font)
        self.pushButton_ofzakaz.setStyleSheet("background-color: rgb(255, 220, 158);")
        self.pushButton_ofzakaz.setObjectName("pushButton_ofzakaz")
        self.comboBox_prodyct = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_prodyct.setGeometry(QtCore.QRect(70, 200, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_prodyct.setFont(font)
        self.comboBox_prodyct.setObjectName("comboBox_prodyct")
        self.lineEdit_kol = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kol.setGeometry(QtCore.QRect(70, 270, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_kol.setFont(font)
        self.lineEdit_kol.setObjectName("lineEdit_kol")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 561, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_fio.setPlaceholderText(_translate("MainWindow", "ФИО"))
        self.lineEdit_phone.setPlaceholderText(_translate("MainWindow", "Телефон"))
        self.pushButton_ofzakaz.setText(_translate("MainWindow", "Оформить заказ"))
        self.lineEdit_kol.setPlaceholderText(_translate("MainWindow", "кол-во"))
